/**
 * Prisma seed script.
 *
 * Enums (Plan, StorageType, DownloadStatus, ActionType) are native PostgreSQL
 * enum types managed by Prisma migrations — they don't need rows in a lookup
 * table. This seed script is a no-op for enums but provides a place to insert
 * any required reference / fixture data for development and testing.
 *
 * Run via: npx prisma db seed
 */

import { PrismaClient, Plan, StorageType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Example: create a default admin user for development
  // (skip if already exists)
  const adminEmail = process.env.SEED_ADMIN_EMAIL ?? 'admin@music.local';
  const existing = await prisma.user.findUnique({ where: { email: adminEmail } });

  if (!existing) {
    // In production you would hash this; for seed purposes we note it here.
    // The actual bcrypt hash is generated by the Auth service on registration.
    // We insert a placeholder hash so the record is valid.
    const bcrypt = await import('bcrypt');
    const passwordHash = await bcrypt.hash(
      process.env.SEED_ADMIN_PASSWORD ?? 'changeme',
      12,
    );

    await prisma.user.create({
      data: {
        email: adminEmail,
        passwordHash,
        name: 'Admin',
        plan: Plan.premium,
        isAdmin: true,
        offlineEnabled: true,
        storageType: StorageType.s3,
      },
    });

    console.log(`Created admin user: ${adminEmail}`);
  } else {
    console.log(`Admin user already exists: ${adminEmail}`);
  }

  console.log('Seeding complete.');
}

main()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
